COMIENZA PROGRAMA java
	SECCION IO
		USANDO STDIO
	SECCION VARIABLES
		DEFINE palabra_buena COMO CADENA
		DEFINE numero COMO ENTERO
	SECCION PROCEDIMIENTO
		palabra_buena ES "casa"
		numero ES 5555
		ESCRIBE palabra ->
		EN SALIDA_ESTANDAR
TERMINA PROGRAMA java