COMIENZA PROGRAMA PRUEBA
	DEFINE D COMO ENTERO
	DEFINE B COMO ENTERO DE 8 BYTES
	DEFINE C COMO ENTERO
	DEFINE E COMO PUNTERO A ENTERO
	DEFINE H COMO ARRAY
	DEFINE PERSONA COMO ESTRUCTURA
		PERSONA.ALTURA COMO ENTERO
		PERSONA.PESO COMO ENTERO
	DEFINE pepe COMO PERSONA
		pepe.altura ES 186
		pepe.pese ES 109
	A ES 4
	A = 9999
	C *= A -= B
	MIENTRAS A<B
		A +== 1
	SI A>B ENTOCES
		SALIR
	SI A==B ENTOCES
		texto = "Hola mundo"
	HABLAR texto
TERMINA PROGRAMA PRUEBA